# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

# Explicitely define languange versions in order to auto install required
# infrastructure like ruby, node, ...:
# - ruby: required by markdownlint hook
# - node: required by markdownlint-cli
default_language_version:
  ruby: 3.2.1
  node: 22.7.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-xml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.41.0"
    hooks:
      - id: markdownlint
        args: ["-f"]
        stages: [pre-commit]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict, feat, fix, doc, perf, refactor, style, test, ci, build, revert, chore]
  - repo: https://github.com/bnjbvr/cargo-machete
    rev: v0.9.2
    hooks:
      - id: cargo-machete
  - repo: https://codeberg.org/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
