# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "OpenSSL",
    "CDLA-Permissive-2.0",
]

targets = [
    "armv7-unknown-linux-gnueabihf"
]

ignore-dev-dependencies = true

private = {ignore = true}
