# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

[workspace]
resolver = "3"
members = [ "libupdated", "libupdated-macros", "updated"]

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "unwind"
codegen-units = 1

[workspace.package]
rust-version = "1.92.0"

[net]
git-fetch-with-cli = true
