# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

[package]
name = "libupdated-macros"
version = "1.0.0"
edition = "2024"
rust-version = "1.92.0"
license = "MIT"
repository = "https://github.com/liebherr-group/updated"
readme = "../README.md"
description = "helper macros for libupdated"
authors = ["Thomas Witte <thomas.witte@liebherr.com>"]
documentation = "https://docs.rs/libupdated-macros/"
categories = ["automotive", "embedded"]

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.41"
syn = { version = "2.0.110", features = ["full"] }
