# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

[book]
authors = ["LDC Connected Systems"]
language = "en"
multilingual = false
src = "src"
title = "updated"
