# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: <text>
# Copyright(c) 2026 Liebherr-Digital Development Center GmbH
# Written by Thomas Witte <thomas.witte@liebherr.com>
# </text>

[target.armv7-unknown-linux-gnueabihf]
runner = "qemu-arm-static"
linker = "arm-linux-gnueabihf-gcc"

[net]
git-fetch-with-cli = true
